name: Sync labels
on: issues

jobs:

  sync_labels:
    name: Sync labels
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
    - uses: lannonbr/issue-label-manager-action@2.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
