name: Lint
on:
  push:
  pull_request:
  schedule:
    # Run linter every week to catch regressions from external dependencies.
    - cron: 17 9 * * 1

jobs:

  lint-markdown:
    name: Lint markdown
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.2
    - uses: avto-dev/markdown-lint@v1.3.1
      with:
        config: '.github/markdown-lint.yaml'
        args: './**/*.md'

  lint-awesome:
    name: Lint Awesome list
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.2
        with:
          # Fetch all history to please linter's age checks.
          fetch-depth: 0
      - run: |
          npx awesome-lint
